name: Apply Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tftest.hcl'
  pull_request:
    paths:
      - '**.tf'
      - '**.tftest.hcl'
  workflow_dispatch:
    inputs:
      run_full_suite:
        description: 'Run full test suite (all apply tests)'
        required: false
        type: boolean
        default: false

env:
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_CLIENT_ID: ${{ secrets.MONGODB_ATLAS_CLIENT_ID }}
  MONGODB_ATLAS_CLIENT_SECRET: ${{ secrets.MONGODB_ATLAS_CLIENT_SECRET }}
  MONGODB_ATLAS_BASE_URL: ${{ secrets.MONGODB_ATLAS_BASE_URL }}

jobs:
  dev-cluster-test:
    name: Dev Cluster Test
    if: ${{ !inputs.run_full_suite }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-terraform
      - name: Run Dev Cluster Test
        run: |
          terraform init
          terraform test -filter=tests/apply_dev_cluster.tftest.hcl -var "org_id=${MONGODB_ATLAS_ORG_ID}"

  tftest-integration-tests:
    name: tftest integration tests
    if: ${{ inputs.run_full_suite }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-terraform
      - name: Run tftest integration tests
        run: just integration-tests
