name: 'Cleanup Terraform Modules Org'

on:
  workflow_dispatch: # workflow can be run manually
  schedule:
    - cron: "0 3 * * *" # workflow runs every day at 03:00 AM

jobs:  
  cleanup-terraform-modules-org:
    runs-on: ubuntu-latest
    steps:
      - name: terraform-provider-mongodbatlas-checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: mongodb/terraform-provider-mongodbatlas
      - name: Cleanup cloud-dev terraform-modules-org
        uses: ./.github/templates/clean-atlas-org
        env:
            MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
            MONGODB_ATLAS_CLIENT_ID: ${{ secrets.MONGODB_ATLAS_CLIENT_ID }}
            MONGODB_ATLAS_CLIENT_SECRET: ${{ secrets.MONGODB_ATLAS_CLIENT_SECRET }}
            MONGODB_ATLAS_BASE_URL: ${{ secrets.MONGODB_ATLAS_BASE_URL }}
