name: Code Health

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  check:
    name: Code Quality & Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-docs
      - uses: ./.github/actions/setup-terraform
      - name: Run all validation checks
        run: just check

  plan-tests:
    name: Terraform Plan Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-terraform
      - name: Run Terraform plan tests
        run: just unit-plan-tests
