name: Code Health

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-terraform
      - run: just validate
      - run: just lint

  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-docs
      - uses: ./.github/actions/setup-terraform
      - name: Check documentation is up-to-date
        run: just check-docs

  plan-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-terraform
      - run: just unit-plan-tests
